[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_SUPABASE_URL = "https://tpoqcxqyolnrkekdnorj.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwb3FjeHF5b2xucmtla2Rub3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTc1OTksImV4cCI6MjA2NTg3MzU5OX0.lefMCOcrGhZIvfB3W9-vpd_wTCUu6GRzl-Gr4IqQ8TA"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"
  targetPort = 3000
  publish = ".next"
  command = "npm run dev"
